2025-03-19 12:56:18,844 : INFO : root : Loading config.
2025-03-19 12:56:18,899 : INFO : ConfigProcessor : Config spec file cache created: C:\Users\duffb\AppData\Local\Temp\config_spec.mpf_cache
2025-03-19 12:56:18,899 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-19 12:56:18,900 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml.
2025-03-19 12:56:18,928 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\mpfconfig.yaml
2025-03-19 12:56:18,929 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml.
2025-03-19 12:56:18,953 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\config\config.yaml
2025-03-19 12:56:18,955 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\cadfdee4981114acd6fff59d1071b59b.mpf_cache
2025-03-19 12:56:19,120 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-03-19 12:56:19,134 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-03-19 12:56:19,134 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\config\attract.yaml.
2025-03-19 12:56:19,151 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\config\attract.yaml
2025-03-19 12:56:19,152 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\ee7db1e8d011f44c876692bb4657f2e9.mpf_cache
2025-03-19 12:56:19,153 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\modes\game\config\game.yaml.
2025-03-19 12:56:19,165 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\modes\game\config\game.yaml
2025-03-19 12:56:19,167 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\9f058d482eac17116727d62a93500be7.mpf_cache
2025-03-19 12:56:19,168 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\base\config\base.yaml.
2025-03-19 12:56:19,182 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\base\config\base.yaml
2025-03-19 12:56:19,183 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\9e006ea23aa21ec68e01f6c49afad9f4.mpf_cache
2025-03-19 12:56:19,184 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_display_loop.yaml.
2025-03-19 12:56:19,201 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_display_loop.yaml
2025-03-19 12:56:19,202 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\fd253b339e263587268891c4dd997fbd.mpf_cache
2025-03-19 12:56:19,202 : INFO : ConfigProcessor : Loading config from file C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_light_show.yaml.
2025-03-19 12:56:19,224 : INFO : ConfigProcessor : Loading config: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine\modes\attract\shows\.\attract_light_show.yaml
2025-03-19 12:56:19,224 : INFO : ConfigProcessor : Config file cache created: C:\Users\duffb\AppData\Local\Temp\5fa2ea82b8edc9fe8478b9f5dddd5453.mpf_cache
2025-03-19 12:56:19,225 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.0
2025-03-19 12:56:19,226 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-19-12-56-18-mpf-T0SHIII.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2025-03-19 12:56:19,226 : INFO : Machine : MPF path: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf
2025-03-19 12:56:19,226 : INFO : Machine : Machine path: C:\Users\duffb\OneDrive\Documents\Python Envs\PinBallWW1\Machine
2025-03-19 12:56:19,226 : INFO : Machine : Platform: win32
2025-03-19 12:56:19,226 : INFO : Machine : Python executable location: C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\python.exe
2025-03-19 12:56:19,226 : INFO : Machine : Python version: 3.11.0 (64-bit)
2025-03-19 12:56:19,232 : INFO : Machine : Initializing MPF...
2025-03-19 12:56:19,864 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,949 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-03-19 12:56:19,949 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 8000, 'prev_value': None, 'change': True}
2025-03-19 12:56:19,949 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 1000, 'prev_value': None, 'change': True}
2025-03-19 12:56:19,949 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.0', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,949 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.0, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,949 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.11.0', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,990 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,990 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,990 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,990 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,990 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-03-19 12:56:19,990 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-03-19 12:56:20,032 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-03-19 12:56:20,032 : INFO : SwitchController : Found active switch: ('3', <Platform.SmartVirtual>) <switch.s_trough1>
2025-03-19 12:56:20,033 : INFO : SwitchController : Found active switch: ('4', <Platform.SmartVirtual>) <switch.s_trough2>
2025-03-19 12:56:20,033 : INFO : SwitchController : Found active switch: ('5', <Platform.SmartVirtual>) <switch.s_trough3>
2025-03-19 12:56:20,036 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-03-19 12:56:20,038 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-03-19 12:56:47,288 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-03-19 12:56:47,289 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-03-19 12:56:47,289 : ERROR : asyncio : Exception in callback EventManager.process_event_queue()
handle: <Handle EventManager.process_event_queue()>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\text_ui.py", line 462, in _bcp_connected
    self.scene.remove_effect(self._pending_bcp_connection)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\asciimatics\scene.py", line 85, in remove_effect
    self._effects.remove(effect)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connected of <mpf.core.text_ui.TextUi object at 0x000001FCF6CDFE00>>, priority=1, kwargs={}, key=UUID('5237d85a-95dd-45f4-a4fd-fe5476cab2cb'), condition=None, blocking_facility=None) for event bcp_clients_connected. list.remove(x): x not in list
2025-03-19 12:56:47,451 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.1', 'prev_value': None, 'change': True}
2025-03-19 12:56:47,451 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.1 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0 or newer)', 'prev_value': None, 'change': True}
2025-03-19 12:56:47,454 : INFO : ball_device.bd_trough : BCH: Initial count: 3
2025-03-19 12:56:47,510 : INFO : ball_device.bd_trough : State: idle
2025-03-19 12:56:47,510 : INFO : Machine : Starting the main run loop.
2025-03-19 12:56:47,511 : INFO : Machine : Shutting down...
2025-03-19 12:56:47,512 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-19 12:56:47,513 : INFO : ball_device.bd_plunger_lane : BCH: Initial count: 0
2025-03-19 12:56:47,514 : INFO : ball_device.bd_plunger_lane : State: idle
2025-03-19 12:56:47,581 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-03-19 12:56:47,612 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-03-19 12:56:47,616 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py:790
handle: <Handle Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py:790>
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2025-03-19 12:56:47,693 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 13, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,694 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 48, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,694 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Lane1'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,696 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Lane2'====== Args={'value': 4, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,698 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Lane3'====== Args={'value': 4, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,699 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Lane4'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,699 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Target1'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,700 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Target2'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,702 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Target3'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,703 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_Target4'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,705 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_drain'====== Args={'value': 6, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,706 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_launcher_button'====== Args={'value': 1, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,708 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_playfield_entry'====== Args={'value': 1, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,709 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough1'====== Args={'value': 1, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,709 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough2'====== Args={'value': 4, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,710 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough3'====== Args={'value': 8, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,710 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_enter'====== Args={'value': 3, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,711 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'average': 124, 'top': [8000, 1000, 0, 0, 0, 0, 0, 0, 0, 0], 'total': 16}, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,711 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane1'====== Args={'value': 34, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,712 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane2'====== Args={'value': 23, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,714 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane3'====== Args={'value': 20, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,714 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Lane4'====== Args={'value': 24, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,714 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target1'====== Args={'value': 64, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,715 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target2'====== Args={'value': 57, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,715 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target3'====== Args={'value': 62, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,716 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_Target4'====== Args={'value': 49, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,718 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_drain'====== Args={'value': 0, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,719 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_launcher_button'====== Args={'value': 89, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,719 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_flipper'====== Args={'value': 95, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,720 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_playfield_entry'====== Args={'value': 198, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,720 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger_lane'====== Args={'value': 132, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,720 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_pointTarget'====== Args={'value': 193, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,721 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_flipper'====== Args={'value': 88, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,721 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough1'====== Args={'value': 109, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,721 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough2'====== Args={'value': 17, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,722 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough3'====== Args={'value': 14, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,722 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_enter'====== Args={'value': 1, 'prev_value': None, 'change': True}
2025-03-19 12:56:47,723 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2025-03-19 12:56:47,724 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-75' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\windows_events.py:591> wait_for=<_OverlappedFuture cancelled>>
2025-03-19 12:56:47,725 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\text_ui.py", line 462, in _bcp_connected
    self.scene.remove_effect(self._pending_bcp_connection)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\asciimatics\scene.py", line 85, in remove_effect
    self._effects.remove(effect)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connected of <mpf.core.text_ui.TextUi object at 0x000001FCF6CDFE00>>, priority=1, kwargs={}, key=UUID('5237d85a-95dd-45f4-a4fd-fe5476cab2cb'), condition=None, blocking_facility=None) for event bcp_clients_connected. list.remove(x): x not in list
2025-03-19 12:56:56,078 : ERROR : root : 
Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 751, in _run_handlers
    result = handler.callback(**merged_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\text_ui.py", line 462, in _bcp_connected
    self.scene.remove_effect(self._pending_bcp_connection)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\asciimatics\scene.py", line 85, in remove_effect
    self._effects.remove(effect)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 794, in _run_loop
    raise self._exception['exception']
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 842, in process_event_queue
    self._process_event(event=event[0],
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 804, in _process_event
    result = self._run_handlers(event, ev_type, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\events.py", line 753, in _run_handlers
    raise EventHandlerException(
mpf.core.events.EventHandlerException: Exception while processing RegisteredHandler(callback=<bound method TextUi._bcp_connected of <mpf.core.text_ui.TextUi object at 0x000001FCF6CDFE00>>, priority=1, kwargs={}, key=UUID('5237d85a-95dd-45f4-a4fd-fe5476cab2cb'), condition=None, blocking_facility=None) for event bcp_clients_connected. list.remove(x): x not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 690, in run
    self._run_loop()
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\machine.py", line 797, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "C:\Users\duffb\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError
